### ISSUE TITLE
list all known gateways?

### ISSUE THREAD

**Issue by thisconnect** [ipfs/public-gateway-checker#14]
hi
should we just list all gateways that are known?

https://ipfs.infura.io/ipfs/QmZbj5ruYneZb8FuR9wnLqJCpCXMQudhSdWhdhp5U1oPWJ

**Comment by VictorBjelkholm** [comment]
Yup! Infura is already listed [https://github.com/ipfs/public-gateway-checker/blob/master/gateways.json#L4] but keep em coming if you know more of them!

**Comment by Mikaela** [comment]
I am aware of there also being [ipfs4uvgthshqonk.onion](http://ipfs4uvgthshqonk.onion/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a) but it doesn't seem to be up at the moment. Source: [Lesson: Access IPFS through Tor gateways (experimental)](https://dweb-primer.ipfs.io/avenues-for-access/lessons/tor-gateways.html) .

But are onion services an exception to all known gateways as they can only be accessed with Tor? How about I2P ones if they exist or Cjdns (I am surprised if they don't exist)?

**Comment by sbani** [comment]
@Mikaela: My gateway is accessible through tor http://ipfskrqqlv5nqbfs.onion/ipfs/{hash}
My tor gateway can only be accessed through tor at the moment.

Example: http://ipfskrqqlv5nqbfs.onion/ipfs/Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z

It's linked to my clearnet gateway `ipfs.netw0rk.io` which is currently down until I figure out how to handle abuse.

**Comment by georgengelmann** [comment]
> I am aware of there also being [ipfs4uvgthshqonk.onion](http://ipfs4uvgthshqonk.onion/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a) but it doesn't seem to be up at the moment. Source: [Lesson: Access IPFS through Tor gateways (experimental)](https://dweb-primer.ipfs.io/avenues-for-access/lessons/tor-gateways.html) .
> 
> But are onion services an exception to all known gateways as they can only be accessed with Tor? How about I2P ones if they exist or Cjdns (I am surprised if they don't exist)?

I have configured a .onion gateway - is it possible to include it in the gateway checker?

http://5sa45npeflx74qmk.onion
