### ISSUE TITLE
Add new ipfs gateway

### ISSUE THREAD

**Issue by ipfsgate** [ipfs/public-gateway-checker#142]
Hi everyone, 
we run a new advanced public IPFS gateway here: 
https://www.ipfsgate.com
https://search.ipfsgate.com/ipfs/hash

We would like to add the gateway to your 'public gateway checker' (https://ipfs.github.io/public-gateway-checker/), but I am not sure that I fully understand how to "upload" updated json file? What exactly means "submit a pull request"? 

Thank you 
Best Regards. 
Adam.

**Comment by jessicaschilling** [comment]
Hi @ipfsgate - there are simple instructions [here](https://github.com/ipfs/public-gateway-checker#adding-a-new-public-gateway) for how to edit the json file at https://github.com/ipfs/public-gateway-checker/blob/master/gateways.json . Once you've done that, and you go to save the file, you'll get a question that looks something like this:

![image](https://user-images.githubusercontent.com/1507828/115417461-df279d80-a1b5-11eb-9930-9bf9513a42b0.png)

Go ahead and follow the workflow for starting a pull request (PR). The pull request is templated, so it'll have some guidance for you help complete the process. Once you submit the PR, someone will review it, check for anything that needs to be changed, and merge the code.
