### ISSUE TITLE
change the positive visual orientation of "online" to something neutral

### ISSUE THREAD

**Issue by autonome** [ipfs/public-gateway-checker#149]
Minor design change:

We currently mark online gateways with ✅ and offline with ❌.

✅ visually connotes "ok" which is different than "online", and maybe stronger than we want to suggest.

Could use 🌍 or something instead?

**Comment by jessicaschilling** [comment]
This will be closed by https://github.com/ipfs/public-gateway-checker/pull/153. @lidel can you please take a quick review?
