### ISSUE TITLE
How can we check wether those public gateway opened API?

### ISSUE THREAD

**Issue by zikunfan** [ipfs/public-gateway-checker#166]
Currently, we can easily check if the public GW support `CORS`, if it is `Online`. 
To my understanding there is still a huge demand on calling those GW's API(like pinata/infura's IPFS GW services), like `/api/v0/add`, Do we have any plan to detect and provide a way to show whether those public GWs allow us to call APIs?

**Comment by Stebalien** [comment]
Not really. These are _public_ gateways, not pinning services. They're for accessing data stored on nodes in the IPFS network, not for storing data on behalf of users.

If you need to store data, you'll need to either host it yourself or pay a pinning service (like Pinata or Infura).
