### ISSUE TITLE
Checker falsely reports missing origin isolation

### ISSUE THREAD

**Issue by SoftCreatR** [ipfs/public-gateway-checker#171]
I've just added my own Gateway ipfs.1-2.dev to the list. Besides the fact, that the server is located in Germany and not USA as reported, it also falsely reports missing origin isolation. However, I've just tested it in my fork by removing everything, except for this specific gateway and there, this isn't an issue at all: https://softcreatr.github.io/public-gateway-checker/

Maybe a problem with the amount of Gateways to be checked synchronously?

**Comment by Kcchouette** [comment]
https://softcreatr.github.io/public-gateway-checker/ seems to not work for me

**Comment by SoftCreatR** [comment]
That's correct, I've deleted the fork. But it was just the same code as used here, but with all nodes removed, except for my own.

**Comment by SoftCreatR** [comment]
Hi, that was correct, yes.

And it's also correct, that my gateway is offline.

And: The reason for the wrong server location is the outdated geo location package and database.
