### ISSUE TITLE
Test with /ipns/ path

### ISSUE THREAD

**Issue by lidel** [ipfs/public-gateway-checker#191]
Sometimes people submit gateway that resolves `/ipfs/` just fine, but fails with `/ipns/en.wikipedia-on-ipfs.org`

Implementation-wise, IPNS test could be done by trying to load Img from `/ipns/en.wikipedia-on-ipfs.org/favicon.ico` (we already have that for `/ipfs`, so just run the same test but for wikipedia favicon)

**Comment by whizzzkid** [comment]
Deployed in #313, fixed ✅
