### ISSUE TITLE
Test Block and CAR response types

### ISSUE THREAD

**Issue by lidel** [ipfs/public-gateway-checker#270]
We should add tests for trustless (verifiable) response types: [application/vnd.ipld.raw](https://www.iana.org/assignments/media-types/application/vnd.ipld.raw) and [application/vnd.ipld.car](https://www.iana.org/assignments/media-types/application/vnd.ipld.car)

Should have tests for requesting both `?format=raw|car` and `Accept: application/vnd.ipld.raw|car` and passing only when both work.

Ref. 

- [feat(gateway): Block and CAR response formats kubo#8758](https://github.com/ipfs/go-ipfs/pull/8758)
- https://github.com/ipfs/specs/blob/main/http-gateways/TRUSTLESS_GATEWAY.md

**Comment by whizzzkid** [comment]
Fixed!
