### ISSUE TITLE
Add pageview metrics to countly

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/public-gateway-checker#306]
We should add public-gateway-checker metrics to county

base level metrics are covered by https://github.com/ipfs/ipfs-gui/issues/125

and eventually more metrics:
- [ ] #334

**Comment by SgtPooki** [comment]
would it make sense to use plausible.io metrics so that users can view uptime/percentages for checks across different gateways?

**Comment by whizzzkid** [comment]
@SgtPooki plausible.io sounds interesting and better than countly as per the sales pitch. But, neither seem to abide by [open-metric standard](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md) is that something to care about?

**Comment by SgtPooki** [comment]
> @SgtPooki plausible.io sounds interesting and better than countly as per the sales pitch. But, neither seem to abide by [open-metric standard](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md) is that something to care about?

I'm not super familiar with open-metric standard, but we're not parsing through metrics ourselves, and should rely on tools that do that for us that have proper GDPR and consent protocols above any particular standard's usage.
