### ISSUE TITLE
geoip (country flags) column is broken

### ISSUE THREAD

**Issue by lidel** [ipfs/public-gateway-checker#317]
Country flags no longer show on  https://ipfs.github.io/public-gateway-checker/

**Comment by whizzzkid** [comment]
This seems to be blocked by: https://github.com/ipfs-shipyard/ipfs-geoip/issues/87 the issue got introduced here: https://github.com/ipfs-shipyard/ipfs-geoip/pull/82/files

**Comment by SgtPooki** [comment]
@whizzzkid can we revert the version of geoip we're using so we can resolve this on public gateway checker?

**Comment by whizzzkid** [comment]
Deployed in #319, fixed ✅

**Comment by lidel** [comment]
@whizzzkid tip: if you include `Closes #319` in the description of your PR, then it will automatically close linked issue when PR is merged. 

See: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by whizzzkid** [comment]
@lidel thanks for the protip. Still getting a hang of GitHub issue management
