### ISSUE TITLE
ipfs about activation?

### ISSUE THREAD

**Issue by ByYasin** [ipfs/public-gateway-checker#320]
Hello, first of all, I can activate all the tools and plugins without any problems, this is super. But although I activate the Rider plugin, I cannot activate the Visual Studio plugin ReSharper .net plugin. Is there a way to enable ReSharper .net?

![chrome_UaitlZ9IIz](https://user-images.githubusercontent.com/28735823/196474253-25be18f2-4d89-4da2-8500-ba9dc092571f.png)

**Comment by ByYasin** [comment]
![chrome_UaitlZ9IIz](https://user-images.githubusercontent.com/28735823/196474190-b6a10994-adac-4b84-a57f-9aca8af494e7.png)

**Comment by ByYasin** [comment]
@ipfs  help?

**Comment by lidel** [comment]
This project does not use .NET nor has any dependency on Visual Studio.
For general IPFS help try  https://discuss.ipfs.io/c/help/13
