### ISSUE TITLE
Warning about ipfs.joaoleitao.org in gateway checker.

### ISSUE THREAD

**Issue by 0xc0de4c0ffee** [ipfs/public-gateway-checker#392]
Chrome is showing this warning after loading gateway checker.

> Deceptive site ahead
Attackers on ipfs.joaoleitao.org may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards). [Learn more](chrome-error://chromewebdata/#)
To get Chrome’s highest level of security, [turn on enhanced protection](chrome-error://chromewebdata/#)
Google Safe Browsing recently [detected phishing](chrome-error://chromewebdata/#) on ipfs.joaoleitao.org. Phishing sites pretend to be other websites to trick you.
You can [report a detection problem](chrome-error://chromewebdata/#) or, if you understand the risks to your security, [visit this unsafe site](chrome-error://chromewebdata/#). 

<img width="930" alt="Screenshot" src="https://user-images.githubusercontent.com/43116881/226177946-5ee37e9d-0352-4ae6-a57e-085a0515b325.png">

**Comment by SgtPooki** [comment]
@BigLep @whizzzkid created https://github.com/ipfs/public-gateway-checker/issues/395 to follow up with potential long-term / automated fix.
