### ISSUE TITLE
Eternum.io is showing as offline even though it's working.

### ISSUE THREAD

**Issue by skorokithakis** [ipfs/public-gateway-checker#4]
I think it's because it's redirecting to the www version. The proper host name is https://www.eternum.io.

**Comment by thisconnect** [comment]
both www. and the other are working. but cors is disabled see https://github.com/ipfs/public-gateway-checker/issues/6

**Comment by skorokithakis** [comment]
I added the CORS header, however it does not get emitted on 301s. Can you change the hostname to https://www.eternum.io?

**Comment by VictorBjelkholm** [comment]
This has been fixed now :) Thanks for spotting it and fixing it quickly!
