### ISSUE TITLE
Pruning dead gateways

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/public-gateway-checker#40]
Thanks @jamiew, for all the Pull requests approved today.

Sadly this added a lot of dead gateways. 
Should somebody consider removing them?

**Comment by jamiew** [comment]
@koalalorenzo I just started testing them to do exactly that, help appreciated

My dead gateways list so far:

* https://xmine128.tk/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://ipfs.doolta.com/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://rx14.co.uk/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://ipns.co/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://gateway.originprotocol.com/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://ipfs.dapps.earth/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://ipfs.works/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://ipfs.work/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://catalunya.network/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://ipfs.netw0rk.io/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://upload.global/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
* https://api.wisdom.sh/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a

I think Origin might have switched to `ipfs.originprotocol.com` but that doesn't seem to work either

New ones to add?

* https://ipfs.augur.casino

**Comment by Kcchouette** [comment]
Add: https://ipfs.ink/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a

**Comment by Kcchouette** [comment]
For me, theses gateways work
- https://ipns.co/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a

**Comment by koalalorenzo** [comment]
<img width="984" alt="screenshot 2019-03-02 at 16 04 20" src="https://user-images.githubusercontent.com/33528/53683766-e2751c00-3d04-11e9-85e2-8e72bd1c18be.png">

I guess some of those depends on the time of the day/period and luck. Most of those gateways are hosted by volunteers, so thei might not be always stable. I guess we have some false positive and false negatives also based on cache. (See the screenshot, the browser cached most of the requests)

**Comment by jamiew** [comment]
Looks like a good chunk of those are CORS failures which would be solved by #6 (testing via image-loading or similar rather than `fetch`)

**Comment by koalalorenzo** [comment]
Anyway, I think we should probably discourage the usage of centralised gateways. I guess that is a different topic.

**Comment by Jorropo** [comment]
For me https://ipns.co/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a doesn't really works, it only redirect to a random other public gateway.

**Comment by koalalorenzo** [comment]
@Jorropo is correct. The source code of some of those IPFS "gateways" is https://github.com/VanVan/ipfsProxyHTTP

**Comment by jamiew** [comment]
CORS support is in and we pruned some of the oldest dead gateways a while back -- gonna call this one closed. 

Thanks all for filing and helping debug!
