### ISSUE TITLE
Shouldn't `lastpubver` just be tied to gateways.json?

### ISSUE THREAD

**Issue by jamiew** [ipfs/public-gateway-checker#41]
Right now it's wrapping `index.html`, `app.json` and `gateways.json`

The `ipfg` tool seems to be using that hash to cache version of gateway.json; is that how it's intended to be used? Hash of the latest list of gateways basically? (that makes sense to me)

Could also wire this up to that new GitHub app for automatically publishing

**Comment by jamiew** [comment]
I'd like to get rid of this; the old `ipfg` tool https://github.com/JayBrown/Tools/blob/master/ipfg/ipfg also has a newer golang version that doesn't rely on `lastpubver` as a cache key. 

I haven't tested it but the bash ipfg doesn't seem to absolutely expect that file either

**Comment by SgtPooki** [comment]
closing this as we no longer use lastpubver. see https://github.com/ipfs/public-gateway-checker/pull/194#discussion_r818831101
