### ISSUE TITLE
CI misconfiguration are preventing releases or updates to the list of gateways used by the frontend.

### ISSUE THREAD

**Issue by 2color** [ipfs/public-gateway-checker#530]
## Problem
- the `test & maybe release` workflow ([source](https://github.com/ipdxco/unified-github-workflows/blob/31914bfda61680988993e1bf503e791342238abe/.github/workflows/js-test-and-release.yml#L190)) does not run the [`release`](https://github.com/ipfs/public-gateway-checker/actions/runs/7829778294/job/21362605297) job

## Background

- We have two workflows that run concurrently: "test & maybe release" and "Gateway Conformance Dashboard"
- Both workflows commit to the `master` branch
  - "test & maybe release": creates a release commit with the changelog
  - "Gateway Conformance Dashboard": creates a commit in the [aggregate job](https://github.com/ipfs/public-gateway-checker/blob/master/.github/workflows/gateway-conformance.yml#L87) which updates the conformance results [example](https://github.com/ipfs/public-gateway-checker/commit/44d369f938f9153b15e8c2f024257f756247162e).
- A race condition between the two running causes the `aggregate` job to fail [example](https://github.com/ipfs/public-gateway-checker/actions/runs/7292094626/job/19872849515) [example](https://github.com/ipfs/public-gateway-checker/actions/runs/7814993311/job/21318822444) because other job already committed to the repo.
- https://github.com/ipfs/public-gateway-checker/pull/529 made the `test & maybe release` workflow run once the conformance one is completed. 
- However, this has likely changed the event that triggers the `test & maybe release` workflow and causes the `release-check` job to prevent a release ([source](https://github.com/ipdxco/unified-github-workflows/blob/31914bfda61680988993e1bf503e791342238abe/.github/workflows/js-test-and-release.yml#L190)) 

## Possible solutions
- Update the conditions for the `test & maybe release` workflow ( a bit annoying because it's in a different repo https://github.com/ipfs/public-gateway-checker/blob/master/.github/workflows/js-test-and-release.yml#L22)
- Something else I haven't thought of because I'm not so familiar with the CI setup here and all the intentions behind it

**Comment by 2color** [comment]
@lidel @SgtPooki Any thoughts on how to proceed? I think I'm missing some context from how this repo was set up.

**Comment by 2color** [comment]
Following discussion with @lidel 

- As it currently stands, we are not using the results from the gateway conformance tests. 
- A quick look at the current results (report.json), shows that the results don't seem to even be correct

Some improvements we could handle:
- Decouple the gateway conformance tests from the frontend's source of truth (gateway.txt)
- Use the gateways.txt in the frontend 
- Clean up the current list of gateways by removing gateways that don't answer to `http HEAD https://ipfs.io/ipfs/bafkqaaa`

**Comment by SgtPooki** [comment]
Yea we have some followup actions from the gateway conformance updates that were made. I haven't had a chance to focus on changes here for a while

**Comment by 2color** [comment]
Closing this as it's not longer a problem. The conformance tests rely on the same source of truth (gateways.json) but aren't blocking releases.
