### ISSUE TITLE
Test CORS 'Access-Control-Allow-Origin' header 

### ISSUE THREAD

**Issue by thisconnect** [ipfs/public-gateway-checker#6]
Error
Failed to load https://www.eternum.io/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ipfs.github.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I'm not 100% sure but the simplest solution could be just loading an img from the gateway (with plain html) with a green checkbox, and listen onerror in case the gateway is down (replace with red offline label).

**Comment by thisconnect** [comment]
thinking about it <img> should work even without javascript :) js could try to fetch `location. pathname` that way the gateways would all cache this test.

**Comment by koalalorenzo** [comment]
It would be nice to have a "Green" "Orange an "red" check to see what they support (writable gateway maybe too?)

**Comment by jamiew** [comment]
This would be a great little upgrade, pull requests welcome

@koalalorenzo is there way to easily test writability? Would one make a POST to maybe pin a file and see what happens?

**Comment by jamiew** [comment]
This was implemented in PR #74
