### ISSUE TITLE
Upgrade this site to the ipfs-gui

### ISSUE THREAD

**Issue by fsdiogo** [ipfs/public-gateway-checker#60]
Hey!

A discussion has been going on at https://github.com/ipfs/ipfs-gui/issues/80, to upgrade this site to a more [ipfs-gui](https://github.com/ipfs/ipfs-gui) flavour.

I've taken a first stab at it and ported it to React. I was going to open a PR here, but as it was a complete rewrite I created a new repo for it.

We are hoping to add more features to it, would you like to keep this as a separate tool or are you ok with merging both or swapping one for the other?

**Comment by jamiew** [comment]
Got a link to the new repo? Don't think any religion on keeping this as-is!

**Comment by andrasfuchs** [comment]
I think this is the repo: https://github.com/fsdiogo/ipfs-infra-status

Live demo: [ipfs-infra-status.surge.sh](http://ipfs-infra-status.surge.sh)

**Comment by jamiew** [comment]
You were first but gonna close in favor of #79 -- happy to switch that around too :)
