### ISSUE TITLE
Consider hosting latest version of this tool on IPNS

### ISSUE THREAD

**Issue by cbluth** [ipfs/public-gateway-checker#8]
Please consider keeping master of this repo on IPNS, much like we see with https://dist.ipfs.io/

**Comment by VictorBjelkholm** [comment]
So dist.ipfs.io doesn't actually use IPNS (the dnslink value ends up being `/ipfs/QmeqJJqSyNKt6d9SFRR1Rec6MNGJX6hdfnhUi2Bphec79Y` as of right now). Are you suggesting that we host the page on IPFS as well?

**Comment by jamiew** [comment]
It's not possible to manage DNS on GitHub pages, where this is hosted, so I'll have to close this as #willnotfix. Solutions for working around that welcome
