### ISSUE TITLE
Looking for additional maintainers

### ISSUE THREAD

**Issue by lazyweirdo** [ipfs/public-gateway-checker#81]
I want to contribute here, because ipfs represents me in many ways ... this is a small project in which i can contribute, kind of grateful to ipfs ... i write this because it takes boringly long for PRs to be merged

It seems to be no active admins for this project, and believe me, everybody who start to know about ipfs, they search for 'public gateways' because it is the first concept you understand, specially if you come from web development ...

You know, you think things like:
- "oh, distributed content, i like it" ... Then you think:
- i would like to contribute by starting a node and sharing a gateway, where can i share it ?

bam ... you reach here ... and you find that in order to add a gateway you have to create a PR, thing only known among programmers and one or two sysadmin :P , think about how many people you know who could share a gateway but would be completely stuck at the moment of creating a PR ... what ? pull req... what ? what does it mean ?

This project seems to be kind of the 'official' list .. (at least the one you reach from google) ... and let me say, it s*cks

Then you want to contribute, only to find that nobody cares about it, and you cannot do it because somebody else have the control ... which goes pretty much against ipfs itself ... it is supposed to be a decentralized system (also philosophically speaking) ... 

Maybe i am the one who is missing something ... can somebody clarify it ?

Is this project kind of a ghost one ? ... what's the point ?

My girlfriend told me
- "surely, they are in the money laundering business" ... to which i answered
- "well, i think they are not selling anything" ...

Then she stroke my face and said
- "never contradict me ... again"
- Fine

So, for short ... i want to contribute but i can't ... i don't want to give up, but you know, you have to do it at some point ...

I don't know who to tag ... sorry if i am tagging people who don't care about it ... 

@daviddias @Stebalien @bonedaddy @lidel @olizilla @vasco-santos @vmx @koalalorenzo @whyrusleeping @jamiew @victorb

**Comment by olizilla** [comment]
> i write this because it takes boringly long for PRs to be merged

I hear you, I know. There is only a few of us, and we're working on *a lot* of things. Right now there is an [0.5.0 go-ipfs release](https://github.com/ipfs/go-ipfs/issues/6776) brewing, a [testground](https://github.com/ipfs/testground) project that aims to test that release on swarms of 10000+ nodes, and [epic refactors](https://github.com/ipfs/js-ipfs/issues/1670#issuecomment-514227039) of the js-ipfs project and the [ipfs documentiation](https://github.com/ipfs/docs#docs-wg-q4-2019-update), and more.

@jamiew has been volunteering to look after this project (thank you!), and he just let us know that he doesn't have much time to do so any more. We'll respond to PRs as quickly as we can.

> think about how many people you know who could share a gateway but would be completely stuck at the moment of creating a PR ... what ? pull req... what ? what does it mean ?

That is a good point! I have not really thought of this project as _the official index_ of all gateways, more of a neat example app that shows other gateways exist, and how you can get the same content from any of them. I'd not considered that it might appear like a blessed list of gateways. We have not verified the other gateways on this list, and at current there isn't a great mechanism for doing so, other than comparing responses for CIDs.

> This project seems to be kind of the 'official' list .. (at least the one you reach from google) ... and let me say, it s*cks

Thank you for working to make it better! 

> Then you want to contribute, only to find that nobody cares about it, and you cannot do it because somebody else have the control ... which goes pretty much against ipfs itself ... it is supposed to be a decentralized system (also philosophically speaking) ...

Yes, that is frustrating. This repo is under the ipfs org so we have to be a careful about what changes we accept, and we are stretched thin at the moment. We'd still love to have your contributions, but we can't guarantee a turn around time on reviews. It sucks, I know. I love your enthusiasm... You are still empowered to fork the repo and make whatever changes you feel... I'd rather you pushed them here as PRs, but part of the philosophy of decentralisation is that you are not beholded to us to merge them here, you can run with your own fork too. See https://github.com/fsdiogo/ipfs-infra-status as an example... it takes the idea of this app and rebuilds it as a react app. Pehaps we should go that way, but both flavour can exist happily.

**Comment by lazyweirdo** [comment]
Yep, do you know how many people is going to make use of my fork ? .... not my girlfriend 😊 ...

Well, never mind ... kisses

**Comment by jamiew** [comment]
Yes like Oli mentioned, I don't have time to be a dedicated maintainer here anymore. I'm still happy to contribute as a I can

I just went through and triaged some of the outstanding PRs and cleaning up some of the outstanding issues. I'm going to rename this ticket too

@lazyweirdo are you in the IPFS IRC, Matrix or Discord channels? It might help to get some more community eyes on this project too, since it does seem to be a common resource for people coming into IPFS

**Comment by godcong** [comment]
what happened?
I'm just wrote a sentence in https://github.com/ipfs/go-ipfs/issues/6776.
I thought it was my fault at first.
I like ipfs very much.

**Comment by godcong** [comment]
Why do I feel like you want me to join?
Is it my illusion? @jamiew
